import { AvatarLoadout, CosmeticItem } from '../types/models';

export const defaultAvatarLoadout: AvatarLoadout = {
  frameId: 'frame-iron',
  faceId: 'face-focus',
  topId: 'top-midnight',
  auraId: 'aura-none',
};

export const cosmeticCatalog: CosmeticItem[] = [
  {
    id: 'frame-iron',
    name: 'Iron Chassis',
    slot: 'frame',
    description: 'Starter badge chassis with clean arcade edges.',
    tone: '#93a4bf',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'face-focus',
    name: 'Focus Sigil',
    slot: 'face',
    description: 'Starter center sigil for a disciplined lifter badge.',
    tone: '#f5f7fb',
    accentTone: '#53d2c2',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'top-midnight',
    name: 'Midnight Stripe',
    slot: 'top',
    description: 'Starter body stripe for your arcade fitness plate.',
    tone: '#1c2a44',
    accentTone: '#8cf26d',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'aura-none',
    name: 'Dormant Halo',
    slot: 'aura',
    description: 'Quiet outer glow until bigger PRs wake it up.',
    tone: '#060911',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'top-pr-gold',
    name: 'Gold Circuit Stripe',
    slot: 'top',
    description: 'Unlocked after your first lifetime PR.',
    tone: '#f2c45a',
    accentTone: '#060911',
    unlockSource: 'pr_milestone',
    prThreshold: 1,
    unlocked: false,
  },
  {
    id: 'frame-champion',
    name: 'Champion Chassis',
    slot: 'frame',
    description: 'Unlocked at 3 lifetime PRs.',
    tone: '#53d2c2',
    unlockSource: 'pr_milestone',
    prThreshold: 3,
    unlocked: false,
  },
  {
    id: 'aura-volt',
    name: 'Volt Halo',
    slot: 'aura',
    description: 'Unlocked at 5 lifetime PRs.',
    tone: '#8cf26d',
    unlockSource: 'pr_milestone',
    prThreshold: 5,
    unlocked: false,
  },
  {
    id: 'face-elite',
    name: 'Elite Crest',
    slot: 'face',
    description: 'Unlocked at 8 lifetime PRs.',
    tone: '#f5f7fb',
    accentTone: '#f2c45a',
    unlockSource: 'pr_milestone',
    prThreshold: 8,
    unlocked: false,
  },
];
