import { AvatarLoadout, CosmeticItem } from '../types/models';

export const defaultAvatarLoadout: AvatarLoadout = {
  frameId: 'frame-iron',
  faceId: 'face-focus',
  topId: 'top-midnight',
  auraId: 'aura-none',
};

export const cosmeticCatalog: CosmeticItem[] = [
  {
    id: 'frame-iron',
    name: 'Iron Frame',
    slot: 'frame',
    description: 'Starter frame for your avatar card.',
    tone: '#93a4bf',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'face-focus',
    name: 'Focus Face',
    slot: 'face',
    description: 'Calm focused faceplate for your lifter identity.',
    tone: '#f5f7fb',
    accentTone: '#53d2c2',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'top-midnight',
    name: 'Midnight Top',
    slot: 'top',
    description: 'Clean dark starter gym top.',
    tone: '#1c2a44',
    accentTone: '#8cf26d',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'aura-none',
    name: 'No Aura',
    slot: 'aura',
    description: 'Start simple and unlock stronger visual effects later.',
    tone: '#060911',
    unlockSource: 'starter',
    unlocked: true,
  },
  {
    id: 'top-pr-gold',
    name: 'Gold Flex Top',
    slot: 'top',
    description: 'Unlocked after your first lifetime PR.',
    tone: '#f2c45a',
    accentTone: '#060911',
    unlockSource: 'pr_milestone',
    prThreshold: 1,
    unlocked: false,
  },
  {
    id: 'frame-champion',
    name: 'Champion Frame',
    slot: 'frame',
    description: 'Unlocked at 3 lifetime PRs.',
    tone: '#53d2c2',
    unlockSource: 'pr_milestone',
    prThreshold: 3,
    unlocked: false,
  },
  {
    id: 'aura-volt',
    name: 'Volt Aura',
    slot: 'aura',
    description: 'Unlocked at 5 lifetime PRs.',
    tone: '#8cf26d',
    unlockSource: 'pr_milestone',
    prThreshold: 5,
    unlocked: false,
  },
  {
    id: 'face-elite',
    name: 'Elite Visor',
    slot: 'face',
    description: 'Unlocked at 8 lifetime PRs.',
    tone: '#f5f7fb',
    accentTone: '#f2c45a',
    unlockSource: 'pr_milestone',
    prThreshold: 8,
    unlocked: false,
  },
];
