import { Quest, RankConfigItem, RewardItem, XpRules } from '../types/models';

export const rankConfig: RankConfigItem[] = [
  {
    tier: 'Bronze',
    minXp: 0,
    color: '#d17b42',
    description: 'Build the habit and keep the streak alive.',
  },
  {
    tier: 'Silver',
    minXp: 800,
    color: '#a3b2c2',
    description: 'Consistency is taking shape.',
  },
  {
    tier: 'Gold',
    minXp: 1800,
    color: '#f2c45a',
    description: 'Strong training momentum with visible progress.',
  },
  {
    tier: 'Platinum',
    minXp: 3200,
    color: '#70d5d0',
    description: 'Elite consistency and standout progression.',
  },
  {
    tier: 'Elite',
    minXp: 5000,
    color: '#8cf26d',
    description: 'Top-tier GymXP grinder.',
  },
];

export const xpRules: XpRules = {
  baseWorkoutXp: 50,
  perSetXp: 5,
  perExerciseXp: 8,
  volumeStepXp: 3,
  volumeStepSize: 800,
  consistencyMultiplier: 4,
  prBonusXp: 28,
  streakBonusCap: 40,
  socialShareXp: 12,
};

export const baseQuestTemplates: Quest[] = [
  {
    id: 'daily-1',
    title: 'Daily Lift',
    description: 'Complete one workout today.',
    cadence: 'daily',
    goalType: 'workouts',
    target: 1,
    progress: 0,
    xpReward: 50,
    currencyReward: 30,
    iconLabel: 'DQ',
    completed: false,
    audience: 'solo',
  },
  {
    id: 'daily-2',
    title: 'Move Big Weight',
    description: 'Accumulate 6000 kg of volume.',
    cadence: 'daily',
    goalType: 'volume',
    target: 6000,
    progress: 0,
    xpReward: 40,
    currencyReward: 20,
    iconLabel: 'VOL',
    completed: false,
    audience: 'solo',
  },
  {
    id: 'daily-3',
    title: 'Share The Win',
    description: 'Post one workout summary to friends.',
    cadence: 'daily',
    goalType: 'social',
    target: 1,
    progress: 0,
    xpReward: 30,
    currencyReward: 15,
    iconLabel: 'SOC',
    completed: false,
    audience: 'solo',
  },
  {
    id: 'weekly-1',
    title: 'Four Day Split',
    description: 'Log four workouts this week.',
    cadence: 'weekly',
    goalType: 'workouts',
    target: 4,
    progress: 0,
    xpReward: 160,
    currencyReward: 100,
    iconLabel: 'WQ',
    completed: false,
    audience: 'solo',
  },
  {
    id: 'weekly-2',
    title: 'PR Hunter',
    description: 'Set three personal records this week.',
    cadence: 'weekly',
    goalType: 'prs',
    target: 3,
    progress: 0,
    xpReward: 120,
    currencyReward: 80,
    iconLabel: 'PR',
    completed: false,
    audience: 'solo',
  },
  {
    id: 'weekly-3',
    title: 'Crew Clash',
    description: 'Your crew needs 20 workouts this week.',
    cadence: 'weekly',
    goalType: 'workouts',
    target: 20,
    progress: 11,
    xpReward: 220,
    currencyReward: 140,
    iconLabel: 'CC',
    completed: false,
    audience: 'community',
  },
];

export const rewardCatalog: RewardItem[] = [
  {
    id: 'reward-1',
    name: 'Carbon Theme',
    description: 'A stealth black workout skin with neon accents.',
    kind: 'theme',
    rarity: 'common',
    cost: 120,
    unlocked: true,
  },
  {
    id: 'reward-2',
    name: 'Elite Banner',
    description: 'Animated profile banner for leaderboard flexing.',
    kind: 'theme',
    rarity: 'rare',
    cost: 240,
    unlocked: false,
  },
  {
    id: 'reward-3',
    name: 'PR Hunter Badge',
    description: 'A permanent badge for lifters who keep progressing.',
    kind: 'badge',
    rarity: 'rare',
    cost: 180,
    unlocked: true,
  },
  {
    id: 'reward-4',
    name: 'Hypertrophy Plan',
    description: 'Unlock a 6-week progression-focused template plan.',
    kind: 'plan',
    rarity: 'epic',
    cost: 320,
    unlocked: false,
  },
  {
    id: 'reward-5',
    name: 'XP Surge',
    description: 'Adds a 10 percent XP boost to your next completed workout.',
    kind: 'boost',
    rarity: 'common',
    cost: 90,
    unlocked: false,
  },
];
